accumulate_grad_batches: 4
adam_epsilon: 1.0e-07
batch_size: 8
classifier_dropout: 0.1
create_token_type_ids: sequential
data_path: ./dataset_splits/
data_type: txt
dataloader_num_workers: 2
dataloader_type: map
gradient_checkpointing: false
learning_rate: 0.001
max_seq_length: 4096
max_steps: 50000
model_name_or_path: allenai/longformer-base-4096
model_type: longformer
no_use_token_type_ids: true
num_frozen_steps: 0
only_preprocess: false
optimizer_type: Adam
pooling_mode: ''
preprocess_resume: only_preprocess
processing_num_threads: 2
processor_no_bert_compatible_cls: true
test_name: test
tokenizer_name: allenai/longformer-base-4096
tokenizer_no_use_fast: false
train_name: train
use_scheduler: null
val_name: val
weight_decay: 1.0e-05
